indi/src/Apdc/ApdcBundle/Form/UserType.php
<?php

namespace Apdc\ApdcBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    /**
     * @inheritdoc
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('shop')
            ->add('roles')
            ->add('enabled', null, [
                'empty_data' => '1'
            ])
        ;
    }

    /**
     * @inheritdoc
     */
    public function getParent()
    {
        return 'FOS\UserBundle\Form\Type\RegistrationFormType';
    }

    /**
     * @inheritdoc
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'csrf_protection' => false,
                'em' => null,
            ]
        );
    }
}

indi/src/Apdc/ApdcBundle/Controller/MerchantsController.php
<?php

namespace Apdc\ApdcBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class MerchantsController extends Controller
{
    public function indexAction(Request $request)
    {
		if(!$this->isGranted('ROLE_INDI_DISPATCH')) {
			return $this->redirectToRoute('root');
		}

		$mage = $this->container->get('apdc_apdc.magento');

		$entity_fromtoMerchant	= new \Apdc\ApdcBundle\Entity\FromToMerchant();
		$form_fromtoMerchant	= $this->createForm(\Apdc\ApdcBundle\Form\FromToMerchant::class, $entity_fromtoMerchant);

		$form_fromtoMerchant->handleRequest($request);

		if ($form_fromtoMerchant->isSubmitted() && $form_fromtoMerchant->isValid()) {
			if ($entity_fromtoMerchant->merchant <> -1) {
				return $this->redirectToRoute('merchantsOne', [
					'id'	=> $entity_fromtoMerchant->merchant,
					'from'	=> $entity_fromtoMerchant->from,
					'to'	=> $entity_fromtoMerchant->to
				]);
			} else {
				return $this->redirectToRoute('merchantsAll', [
					'from'	=> $entity_fromtoMerchant->from,
					'to'	=> $entity_fromtoMerchant->to
				]);
			}
		}

		return $this->render('ApdcApdcBundle::merchants/index.html.twig', [
			'forms' => [
				$form_fromtoMerchant->createView(),
			]
		]);
    }

    public function merchantsOneAction(Request $request, $id, $from, $to)
    {
   		if(!$this->isGranted('ROLE_INDI_DISPATCH')) {
			return $this->redirectToRoute('root');
		}

		$mage = $this->container->get('apdc_apdc.magento');

		$session	= $request->getSession();
		$pdforder	= $this->container->get('apdc_apdc.pdforder');
		
		$entity_fromtoMerchant	= new \Apdc\ApdcBundle\Entity\FromToMerchant();
		$form_fromtoMerchant	= $this->createForm(\Apdc\ApdcBundle\Form\FromToMerchant::class, $entity_fromtoMerchant, [
			'action' => $this->generateUrl('merchantsIndex')
		]);

		$form_fromtoMerchant->get('from')->setData($from);
		$form_fromtoMerchant->get('to')->setData($to);
		$form_fromtoMerchant->get('merchant')->setData($id);

		$merchants = $mage->getMerchantsOrders($id, $from, $to);

		/* Generation PDF commercant */
		$defaultDataPDF = array('message' => 'Send');
		$formPDF = $this->createFormBuilder($defaultDataPDF)
				->add("Send", SubmitType::class, array(
					'label' => 'Envoyer PDF',
					'attr' => array(
						'class' => 'btn btn-lg btn-success',
						'onclick' => 'return confirm("Confirmer l\'envoi de PDF ?")',
					)
				))
				->getForm();
		$formPDF->handleRequest($request);

		if ($formPDF->isSubmitted() && $formPDF->isValid()) {
			
			$pdforder->sendPdfByMerchant($merchants);

			$session->getFlashBag()->add('success', 'PDF bien envoyé');
			return $this->redirectToRoute('merchantsOne', [
					'id'	=> $id,
					'from'	=> $from,
					'to'	=> $to
			]);
		}
		/* FIN PDF */


		return $this->render('ApdcApdcBundle::merchants/one.html.twig', [
			'forms' => [
				$form_fromtoMerchant->createView(),
			],
			'merchants' => $merchants,
			'formPDF' 	=> $formPDF->createView(),
		]);
    }

    public function merchantsAllAction(Request $request, $from, $to)
    {
	
		if(!$this->isGranted('ROLE_INDI_DISPATCH')) {
			return $this->redirectToRoute('root');
		}
		
		$mage = $this->container->get('apdc_apdc.magento');

		$entity_fromtoMerchant	= new \Apdc\ApdcBundle\Entity\FromToMerchant();
		$form_fromtoMerchant	= $this->createForm(\Apdc\ApdcBundle\Form\FromToMerchant::class, $entity_fromtoMerchant, [
			'action' => $this->generateUrl('merchantsIndex')
		]);

		$form_fromtoMerchant->get('from')->setData($from);
		$form_fromtoMerchant->get('to')->setData($to);

		return $this->render('ApdcApdcBundle::merchants/all.html.twig', [
			'forms' => [
				$form_fromtoMerchant->createView(),
			],
			'merchants' => $mage->getOrdersByMerchants(-1, $from, $to),
			'shop_url'		=> \Mage::getBaseUrl().'../index.php/admin/petitcommisadmin/commercant_shop/edit/id_shop/',
			'manager_url'	=> \Mage::getBaseUrl().'../index.php/admin/petitcommisadmin/commercant_contact/edit/id_contact/',

		]);
    }

}

indi/src/Apdc/ApdcBundle/Resources/views/merchants/all.html.twig
{% extends 'ApdcApdcBundle::base.html.twig' %}
{% use 'ApdcApdcBundle::menu/default.html.twig' %}

{% block body %}
	<div class="container">
	<h1> Liste des commandes par magasins </h1><br>
	<div class="space-between">
		<div>{% include 'ApdcApdcBundle::forms/default.html.twig' %}</div>
		<div>{% include 'ApdcApdcBundle::tool/produit_fragile.html.twig' %}</div>
	</div>	

		<hr>

		{% for merchant_id, merchant in merchants %}
			<table style="width:100%">
				<tr>
					<th>
						{# Nb commandes/commercant == taille du tableau 'orders' #}
						{% set nb_commandes_commercant = merchant.orders|length %}
						{% set commandes_msg = "" %} 
											
						{% if nb_commandes_commercant == 0 %}
							{% set commandes_msg %}<div></div>{% endset %}
						{% else %}
							{% set commandes_msg %}<div style="color:red">{{ nb_commandes_commercant ~ " commande(s) "}}</div>{% endset %}
						{% endif %}

						<div style="display:inline-block">
							<h2>
								{% if merchant.blacklist %}
									<i class="fa fa-exclamation-circle" aria-hidden="true" title="Historique de problèmes sur la préparation de commande, à appeler systématiquement si commandes." style="color:red;"></i>
								{% endif %}
								<a href="#{{ merchant_id|replace({' ': '_', "'": '_', '&': '_'}) }}" data-toggle="collapse">{{ merchant.name }}</a>
							</h2>
						</div>
						<div style="display:inline-block; margin-left:8px;"><a href="#{{ merchant_id|replace({' ': '_', "'": '_', '&': '_'}) ~ "horaires" }}" data-toggle="collapse"><i class="fa fa-calendar" aria-hidden="true"></i></a></div>
						<div><h4>{{ commandes_msg }}</h4></div>
					</th>
				</tr>
				<tr>
					<td>
						<div id="{{ merchant_id|replace({' ': '_', "'": '_', '&': '_'}) ~ "horaires" }}" class="store collapse">
							<div>{{ merchant.timetable|raw }}</div>
						</div>

						<div id="{{ merchant_id|replace({' ': '_', "'": '_', '&': '_'}) }}" class="store collapse">
							<div class="merchant{{ (merchant.active==0) ? " error" : "" }}">
									<label>
										<h3><a href={{ shop_url ~ merchant.shop_id }} target="_blank">{{ "Fiche commercant Magento" }}</a></h3>
										<h4><a href={{ manager_url ~ merchant.manager_id }} target="_blank">{{ merchant.manager_name }}: <a href="tel:{{ merchant.phone }}">{{ merchant.phone }}</a> / <a href="tel:{{ merchant.mobile }}">{{ merchant.mobile }}</a></h4>
									<h4 style="color:red;">{{ merchant.warning_days }}</h4></label><br/>
									{% for order_id, order in merchant.orders %}
										<table style="width: 100%">
											<tr>
												<td style="width:40%">
													<a href="#{{ order_id ~ "-" ~ loop.parent.merchant.shop_id }}" data-toggle="collapse">
														<label>{{ order_id ~" "~ order.first_name ~" "~ order.last_name }}</label>
													</a>
												</td>
												<td style="width:30%">
													<label>{{"Nombre d'articles : " ~ order.total_quantite }}</label>
												</td>
												<td style="width:30%">
													<label>{{"Total : " ~ order.total_prix ~ "€"}}</label>
												</td>
											</tr>
											<tr>
												<td colspan="3">
													<div id="{{ order_id ~ "-" ~ loop.parent.merchant.shop_id }}" class="order collapse">
														<table class="table">
															<tr>
																<td style="width: 50%">
																	<table class="table" style="width:50%">
																		<tr>
																			<td><b>Commande N°</b></td>
																			<td><a href="{{path('ordersOne', {id: order_id})}}" target="_blanc">{{ order_id }}</a></td>
																		</tr>
																		<tr>
																			<td><b>Client</b></td>
																			<td>{{ order.first_name ~" "~ order.last_name }}</td>
																		</tr>
																		<tr>
																			<td><b>Prise de Commande</b></td>
																			<td>{{ order.order_date }}</td>
																		</tr>
																		<tr>
																			<td><b>Date de livraison</b></td>
																			<td>{{ order.delivery_date }}</td>
																		</tr>
																		<tr>
																			<td><b>Creneau de livraison</b></td>
																			<td>{{ order.delivery_time }}</td>
																		</tr>
																		<tr>
																			<td><b>Remplacement équivalent</b></td>
																			<td>{{ (order.equivalent_replacement == 1) ? "oui" : "non" }}</td>
																		</tr>
																	</table>
																</td>
																<td style="width: 50%">
																	<table class="table">
																		<tr>
																			<td><b>Adresse de Livraison</b></td>
																			<td><a href="https://www.google.com/maps?q={{order.address}}" target="_blanc">{{ order.address }}</a></td>
																		</tr>
																		<tr>
																			<td><b>Telephone</b></td>
																			<td>{{ order.phone }}</td>
																		</tr>
																		<tr>
																			<td><b>Batiment & Etage</b></td>
																			<td>Bat: {{ order.batiment }}, Etage: {{ order.etage }}</td>
																		</tr>
																		<tr>
																			<td><b>Codes porte</b></td>
																			<td>Code Porte 1: {{ order.codeporte1 }}, Code Porte 2: Code Porte 1: {{ order.codeporte2 }}</td>
																		</tr>
																		<tr>
																			<td><b>Infos Complémentaires</b></td>
																			<td>{{ order.info }}</td>
																		</tr>
																		<tr>
																			<td><b>Quartier</b></td>
																			<td>{{ order.store }}</td>
																		</tr>
																	</table>
																</td>
															</tr>
														</table>
														<table class="table table-striped">
															<tr>
																<th>Produit</th>
																<th>Quantite</th>
																<th>Description</th>
																<th>Prix</th>
																<th>Total</th>
																<th>Commentaire</th>
															</tr>
															{% for product in order.products %}
															{% if (product.produit_fragile == 1) or (product.produit_fragile_referentiel == 1) %}
																<tr style="background-color:rgba(255, 165, 0, 0.7)">
															{% else %}
																<tr>
															{% endif %}
																	<td>{{ product.nom }}</td>
																	<td>{{ product.quantite }}</td>
																	<td>{{ product.description }}</td>
																	<td>{{ product.prix_unitaire ~"€ (" ~ product.prix_kilo~")" }}</td>
																	<td>{{ product.prix_total ~"€" }}</td>
																	<td>{{ product.comment }}</td>
																</tr>
															{% endfor %}
															<tr>
																<td><b>TOTAL</b></td>
																<td colspan="3"><b>{{ order.total_quantite }}</b></td>
																<td colspan="2"><b>{{ order.total_prix }}</b></td>
															</tr>
														</table>
													</div>
												</td>
											</tr>
										</table>
									{% endfor %}
							</div>
						</div>
					</td>
				</tr>
			</table>
		{% endfor %}

	</div>
{% include 'ApdcApdcBundle::menu/footer.html.twig' %}
{% endblock %}

indi/src/Apdc/ApdcBundle/Resources/views/merchants/index.html.twig
{% extends 'ApdcApdcBundle::base.html.twig' %}
{% use 'ApdcApdcBundle::menu/default.html.twig' %}

{% block body %}
	<div class="container">
		<h1> Liste des commandes par magasins </h1><br>
		<div class="row">
			<div class="col-md-8">{% include 'ApdcApdcBundle::forms/default.html.twig' %}</div>
			<div class="col-md-4"></div>
		</div>	
	</div>

{% include 'ApdcApdcBundle::menu/footer.html.twig' %}
{% endblock %}

indi/src/Apdc/ApdcBundle/Resources/views/merchants/one.html.twig
{% extends 'ApdcApdcBundle::base.html.twig' %}

{% use 'ApdcApdcBundle::menu/default.html.twig' %}

{% block body %}
	<div class="container">
	<h1> Liste des commandes par magasins </h1><br>
	<div class="space-between">
		<div>{% include 'ApdcApdcBundle::forms/default.html.twig' %}</div>
		<div>{% include 'ApdcApdcBundle::tool/produit_fragile.html.twig' %}</div>
	</div>
	{{ form(formPDF) }}
		<hr/>
		{% for store_name, mercs in merchants %}
			{% for merchant_id, merchant in mercs %}
				<div class="merchant">
					<label>
						<div style="display:inline-block"><h3>
							{% if merchant.blacklist %}
								<i class="fa fa-exclamation-circle" aria-hidden="true" title="Historique de problèmes sur la préparation de commande, à appeler systématiquement si commandes." style="color:red;"></i>
							{% endif %}
							{{ merchant.name }} - clients de 	{{store_name}}
						</h3></div>
						<div style="display:inline-block; margin-left:8px;"><a href="#{{ merchant_id|replace({' ': '_', "'": '_', '&': '_'}) ~ "horaires" }}" data-toggle="collapse"><i class="fa fa-calendar" aria-hidden="true"></i></a></div>

						<h4 style="color:red;">{{ merchant.warning_days }}</h4>
						{% if merchant.orders|length == 0 %}
							<h4>Pas de commande</h4>
						{% else %}
							<h4 style="color:red">{{ merchant.orders|length ~ " commande(s)" }}</h4>
						{% endif %}
					</label>

					<div id="{{ merchant_id|replace({' ': '_', "'": '_', '&': '_'}) ~ "horaires" }}" class="store collapse">
							<div>{{ merchant.timetable|raw }}</div>
					</div>

					<br/>
					{% for order_id, order in merchant.orders %}
						<table style="width:100%">
							<tr>
								<td style="width:40%">
									<a href="#{{ order_id}}" data-toggle="collapse">
										<label>{{ order_id ~" "~ order.first_name ~" "~ order.last_name }}</label>
									</a>
								</td>
								<td style="width:30%">
									<label>{{"Nombre d'articles : " ~ order.total_quantite }}</label>
								</td>
								<td style="width:30%">
									<label>{{"Total : " ~ order.total_prix }}</label>
								</td>
							</tr>
							<tr>
								<td colspan="3">
									<div id="{{ order_id }}" class="order collapse">
										<table class="table">
											<tr>
												<td style="width: 50%">
													<table class="table" style="width:50%">
														<tr>
															<td><b>Commande N°</b></td>
															<td><a href="{{path('ordersOne', {id: order_id})}}" target="_blanc">{{ order_id }}</a></td>
														</tr>
														<tr>
															<td><b>Client</b></td>
															<td>{{ order.first_name ~" "~ order.last_name }}</td>
														</tr>
														<tr>
															<td><b>Prise de Commande</b></td>
															<td>{{ order.order_date }}</td>
														</tr>
														<tr>
															<td><b>Date de livraison</b></td>
															<td>{{ order.delivery_date }}</td>
														</tr>
														<tr>
															<td><b>Creneau de livraison</b></td>
															<td>{{ order.delivery_time }}</td>
														</tr>
														<tr>
															<td><b>Remplacement équivalent</b></td>
															<td>{{ (order.equivalent_replacement == 1) ? "oui" : "non" }}</td>
														</tr>
													</table>
												</td>
												<td style="width: 50%">
													<table class="table">
														<tr>
															<td><b>Adresse de Livraison</b></td>
															<td><a href="https://www.google.com/maps?q={{order.address}}" target="_blanc">{{ order.address }}</a></td>
														</tr>
														<tr>
															<td><b>Telephone</b></td>
															<td>{{ order.phone }}</td>
														</tr>
														<tr>
															<td><b>Batiment & Etage</b></td>
															<td>Bat: {{ order.batiment }}, Etage: {{ order.etage }}</td>
														</tr>
														<tr>
															<td><b>Codes porte</b></td>
															<td>Code Porte 1: {{ order.codeporte1 }}, Code Porte 2: Code Porte 1: {{ order.codeporte2 }}</td>
														</tr>
														<tr>
															<td><b>Infos Complémentaires</b></td>
															<td>{{ order.info }}</td>
														</tr>
													</table>
												</td>
											</tr>
										</table>
										<table class="table table-striped">
											<tr>
												<th>Produit</th>
												<th>Quantite</th>
												<th>Description</th>
												<th>Prix</th>
												<th>Total</th>
												<th>Commentaire</th>
											</tr>
											{% for product in order.products %}
											{% if (product.produit_fragile == 1) or (product.produit_fragile_referentiel == 1) %}
												<tr style="background-color:rgba(255, 165, 0, 0.7)">
											{% else %}
												<tr>
											{% endif %}
													<td>{{ product.nom }}</td>
													<td>{{ product.quantite }}</td>
													<td>{{ product.description }}</td>
													<td>{{ product.prix_unitaire ~ "€ (" ~ product.prix_kilo~")" }}</td>
													<td>{{ product.prix_total }}</td>
													<td>{{ product.comment }}</td>
												</tr>
											{% endfor %}
											<tr>
												<td><b>TOTAL</b></td>
												<td colspan="3"><b>{{ order.total_quantite }}</b></td>
												<td colspan="2"><b>{{ order.total_prix }}</b></td>
											</tr>
										</table>
									</div>
								</td>
							</tr>
						</table>
					{% endfor %}
				</div>
			{% endfor %}
		{% endfor %}
	</div>
{% include 'ApdcApdcBundle::menu/footer.html.twig' %}
{% endblock %}